server:
  port: 8888
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: subscription
    password: RHjhryLXG7FrHMJB
    url: jdbc:mysql://localhost:3306/subscription?useUnicode=true&characterEncoding=utf8